"""Updated Models

Revision ID: 623ae202fd00
Revises: f25ef2541c9f
Create Date: 2024-11-20 21:55:11.951279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '623ae202fd00'
down_revision = 'f25ef2541c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Review_Images', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour', sa.Integer(), nullable=True))
        batch_op.drop_column('tour_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('tour')

    with op.batch_alter_table('Review_Images', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
