"""Package

Revision ID: 88d330676c4f
Revises: 
Create Date: 2024-11-20 19:11:40.773235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88d330676c4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TourPackage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toperator_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('package_img', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index('idx_tour_package', ['toperator_id'], unique=False)
        batch_op.create_foreign_key(None, 'Tour_Operator', ['toperator_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('exclusion')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('inclusion')
        batch_op.drop_column('itinerary')
        batch_op.drop_column('estimated_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TourPackage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('itinerary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inclusion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exclusion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_tour_package')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('package_img')
        batch_op.drop_column('toperator_id')

    # ### end Alembic commands ###
